### ISSUE TITLE
the generated image collapse

### ISSUE THREAD

**Issue by acumenleo** [cubiq/ComfyUI_InstantID#100]
I installed the instantid step by step, and I loaded the basic workflow and change the  sdxl model,  but the image collapsed. 
the result image like that:
<img width="680" alt="Screen Shot 2024-03-17 at 11 17 03" src="https://github.com/cubiq/ComfyUI_InstantID/assets/41881626/34d0c06d-1ca5-4aed-a213-4922c6e52800">

and this is the workflow:
![workflow (5)](https://github.com/cubiq/ComfyUI_InstantID/assets/41881626/ef99d68d-1109-4c1a-a000-3ccc6578c7ec)

I check the instantid model file and change the sampler parameters, but it still doesn't work. could you help me check this issue, thank you

**Comment by cubiq** [comment]
duplicate https://github.com/cubiq/ComfyUI_InstantID/issues/85

**Comment by acumenleo** [comment]
it works, thanks a lot

**Comment by ykhasia** [comment]
which version of comfyui updated ?
