### ISSUE TITLE
Face Analysis always takes a long time, is this normal?

### ISSUE THREAD

**Issue by henji-henji** [cubiq/ComfyUI_InstantID#101]
I've noticed that the first time I run into Face Analysis, it always takes a long time to load, is this normal?
( The first time I run a workflow it's slow, or if I run this workflow after I've run other workflows it does the same thing. )

Another confusion is, I see that the output from the cmd is
`Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}`
But my provider setting is CUDA, is this normal?

**Comment by cubiq** [comment]
you probably need to update protobuf

**Comment by henji-henji** [comment]
> you probably need to update protobuf

Solved! Thank you very much!
