### ISSUE TITLE
implement pose-based pictures based on the complete skeleton pose

### ISSUE THREAD

**Issue by wangyanmeego** [cubiq/ComfyUI_InstantID#103]
I want InstantID to implement pose-based pictures based on the complete skeleton pose, rather than just based on the face pose.Like openPose in comfyui. Could you please provide some ideas for implementation? Thank you very much.

**Comment by ParthGandhi** [comment]
[Watch this](https://youtu.be/wMLiGhogOPE?si=tIS2pBAHe5ingdKE&t=484)
