### ISSUE TITLE
idk how to fix missed nodes 

### ISSUE THREAD

**Issue by ghoztlyx** [cubiq/ComfyUI_InstantID#104]
![imagen_2024-03-21_030240287](https://github.com/cubiq/ComfyUI_InstantID/assets/164002274/aa1cc398-c8cd-4c58-9567-948ef51972e5)

**Comment by cubiq** [comment]
insightface is not probably installed

**Comment by cubiq** [comment]
closing for now feel free to reopen if you still have issues
