### ISSUE TITLE
Difference in nodes compared to the shared workflows

### ISSUE THREAD

**Issue by anwoflow** [cubiq/ComfyUI_InstantID#107]
<img width="735" alt="image" src="https://github.com/cubiq/ComfyUI_InstantID/assets/122524284/1a6536c5-8226-4bcb-9853-f083285d061e">
Left is the node loaded from the workflow, right is the version I get when I add a new node. 
Seems like there has been an update that changed things around and I assumed all it needed is to put the image in image_features and the face feature analysis happened under the hood, so to speak. But in practice it stopped working. 

and just trying to run the basic workflow will give me error `'- Required input is missing: image_features'` 
but all inputs are hooked up.

**Comment by anwoflow** [comment]
and trying to hook up the updated node, with fewer inputs 
option 1 - directly hooking up face image to image_features -doesn't work at all
<img width="1437" alt="image" src="https://github.com/cubiq/ComfyUI_InstantID/assets/122524284/fc6b2341-b285-4fc1-848a-6abcef1fdf6b">
option 2 - face image connected to face keypoints preprocessor and then to Image_features - no face detected error 
<img width="831" alt="image" src="https://github.com/cubiq/ComfyUI_InstantID/assets/122524284/977eee62-0ce2-4ede-9429-e6e29d9a8a47">

**Comment by chenzxcw** [comment]
i have the same problem,i think it's a version problem.the left is the last version.

**Comment by quqiufeng** [comment]
same problem

**Comment by cubiq** [comment]
please update the extension, refresh the browser tab to clear the cache, delete the old nodes and recreate them.
