### ISSUE TITLE
Why do I get an abnormal image after I run the workflow?

### ISSUE THREAD

**Issue by sakiyo18** [cubiq/ComfyUI_InstantID#115]
![1](https://github.com/cubiq/ComfyUI_InstantID/assets/39026267/9d85c659-6b5d-4f44-a877-846ace091f9a)
![2](https://github.com/cubiq/ComfyUI_InstantID/assets/39026267/5be74ed0-8a8b-458f-a59c-d8aeccfa6fc9)

**Comment by cubiq** [comment]
duplicate https://github.com/cubiq/ComfyUI_InstantID/issues/76
