### ISSUE TITLE
error occured when loading the graph from instantid

### ISSUE THREAD

**Issue by Celunnn** [cubiq/ComfyUI_InstantID#117]
it says,following node types were not found:

ApplyInstantID
InstantIDModelLoader
InstantIDFaceAnalysis
Nodes that have failed to load will show as red on the graph.

does anybody know what the problem is?

**Comment by cubiq** [comment]
you probably don't have instantid installed

**Comment by Celunnn** [comment]
> you probably don't have instantid installed

i have installed instantid,but it seems there's an error,i try to fix it and still no better,what the problem is?

**Comment by cubiq** [comment]
I think the problem is with insightface

**Comment by Celunnn** [comment]
thanks fixed

**Comment by Tiago4D** [comment]
> thanks fixed

Hi! Can you say me how to solve? is not working here, 

B.R.

Tiago
