### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by ziziguai** [cubiq/ComfyUI_InstantID#119]
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/12597310/5dd1a437-ec30-4372-b5b5-ef6b0b0bd263)
i have update instantid and comfyui but it not works

**Comment by LukeG89** [comment]
What kind of checkpoint are you using? InstantID only works with SDXL

**Comment by ziziguai** [comment]
ok,sdxl is fine.thanks
