### ISSUE TITLE
output image is noise

### ISSUE THREAD

**Issue by AhmedMoustafa1** [cubiq/ComfyUI_InstantID#12]
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/18029545/fcc0d679-8a4b-4bc2-9620-f5491eee6d1e)

**Comment by hortom** [comment]
Is this supposed to be an LCM model with 7 steps?
If **yes**, then the sampler should be LCM, isn't it?
If **no**, then try 25-30 steps, `dpmpp_3m_sde_gpu` sampler and `exponential` scheduler.

**Comment by cubiq** [comment]
duplicate https://github.com/cubiq/ComfyUI_InstantID/issues/5

**Comment by aziib** [comment]
mine was too, but i've update the comfy ui incliding the custom nodes like controlnets ip-adapter and the others and it worked fine.
if you using normal sdxl model change the steps to 20 and cfg to 7
