### ISSUE TITLE
Import failed for Insight module mesh_core_cython

### ISSUE THREAD

**Issue by Kiran-KumarS** [cubiq/ComfyUI_InstantID#120]
When I tried to Install InstandID(Both from comfyui manager and git cloning) the installation seemed to work fine, but each time when i open the comfyui bat file i get the error "**ImportError: DLL load failed while importing mesh_core_cython: The specified module could not be found**.". I tried checking all over the internet but did not get any lead to solve the issue. Below is the full logs of comfyui

`D:\Comfyui\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-03-29 18:24:18.013496
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: D:\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: D:\Comfyui\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.1 seconds: D:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 16197 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI Revision: 2045 [b7b55931] | Released on '2024-03-04'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Traceback (most recent call last):
  File "D:\Comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 14, in <module>
    from insightface.app import FaceAnalysis
  File "D:\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "D:\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "D:\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "D:\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "D:\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 10, in <module>
    from . import io
  File "D:\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\io.py", line 10, in <module>
    from .cython import mesh_core_cython
ImportError: DLL load failed while importing mesh_core_cython: The specified module could not be found.

Cannot import D:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID module for custom nodes: DLL load failed while importing mesh_core_cython: The specified module could not be found.

Import times for custom nodes:
   0.3 seconds: D:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.8 seconds (IMPORT FAILED): D:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json`

**Comment by cubiq** [comment]
you are probably missing the cython package or you have a version mismatch

**Comment by Kiran-KumarS** [comment]
The cython package is available and is upgraded to the latest 
` D:\Comfyui\ComfyUI_windows_portable>python_embeded\python.exe  -m pip install --upgrade cython
Requirement already satisfied: cython in d:\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (3.0.9)

D:\Comfyui\ComfyUI_windows_portable>`

Also I had tried to reinstalling comfyui with latest available git package and then tried to run, but still faced the same issue

**Comment by cubiq** [comment]
I would try to reinstall insightface, something went wrong

**Comment by Kiran-KumarS** [comment]
I just did the uninstall and install with pip, But still the same error. The version is 0.7.3

**Comment by Kiran-KumarS** [comment]
fixed now, Just had to reinstall insightface with the whl package and it is fine
`python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl`

**Comment by curtwagner1984** [comment]
> fixed now, Just had to reinstall insightface with the whl package and it is fine `python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl`

God bless the people who manage to solve their own problem and them go back and actually post what they did to resolve it.
I had the same problem and this solved it.

The wheel file can be found here:
https://huggingface.co/hanamizuki-ai/insightface-releases/blob/main/insightface-0.7.3-cp311-cp311-win_amd64.whl

**Comment by aihoom** [comment]
I tried the above method but failed

**Comment by NOTlinnkoln** [comment]
agree didn't work for me too

**Comment by NOTlinnkoln** [comment]
also updating cython ruining Impact pack
