### ISSUE TITLE
Slower performance if ControlNet is used after InstantID ( vs before InstantID )

### ISSUE THREAD

**Issue by JorgeR81** [cubiq/ComfyUI_InstantID#121]
If I use ControlNet before InstantID performance is good ( about as fast as FaceID ).

But, if I use ControlNet after InstantID ( like on the example workflow ) performance is worse ( about twice as slow ).

Performance degradation even is more noticable if I use an image batch, in a more complex workflow ( at least 5 times slower ).

Is that just my old gpu ( GTX 1070 ) or can it be optimized ?

I have very similar results, independently from the ControlNet position. 

But using ControlNet after InstantID, it's more convenient ( e.g. if we want to use a second KSampler, as an upscaler / refiner, with a ControlNet, only at that second stage ).

**Comment by cubiq** [comment]
I need to check on this. I have pushed a new update that might fix this

**Comment by JorgeR81** [comment]
This seems to be fixed now.
