### ISSUE TITLE
Bad image 

### ISSUE THREAD

**Issue by ykhasia** [cubiq/ComfyUI_InstantID#127]
As you can see below screenshot, generated a bad image.. nothing could be shown, what's wrong?

![image](https://github.com/cubiq/ComfyUI_InstantID/assets/52735731/aaab4172-49ec-42ef-930d-676c452fce7c)

**Comment by cubiq** [comment]
this was answered so many times please check the closed issues like this https://github.com/cubiq/ComfyUI_InstantID/issues/85
