### ISSUE TITLE
I can't find the IPAdapter model for the FACEID PORTRAIT preset

### ISSUE THREAD

**Issue by VLevithan** [cubiq/ComfyUI_InstantID#128]
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/160181737/6eb4bb38-b4f4-4b7e-b520-4b2d907fc6c7)
Hi! You can see everything in the screenshot. All other models found, downloaded and installed, all work except this one. Where can I get this model?

**Comment by cubiq** [comment]
this is not an instantID issue, check the IPAdapter repository
