### ISSUE TITLE
FaceAnalysis.__init__() got an unexpected keyword argument 'providers'

### ISSUE THREAD

**Issue by Dekita** [cubiq/ComfyUI_InstantID#131]
Hi, I'm able to run my workflow completely fine in my local test setup, but when I try to deploy the same setup to my serverless environment, I get the following error message;
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/8195694/9571ed78-3d7d-4661-bddd-c8a569776dcb)

I'm not entirely sure what could possibly be causing this issue, and I've been raking my brain for a few days trying to get this working serverless. Would greatly appreciate any insight you may be able to give as to what might cause this.. 

Many thanks <3

**Comment by Dekita** [comment]
Seems that making sure that instantid was requiring insightface v0.7.3 solved this issue :)

**Comment by vesper8** [comment]
In my case, running `pip install insightface` was always installing `insightface===0.2.1`

I then ran `pip install insightface==0.7.3` and that installed the latest version and then the problem went away

**Comment by jelling** [comment]
Same issue, also resolved by specifying the `insightface` version. Likely culprit is this [year old issue in insightface repo](https://github.com/deepinsight/insightface/issues/2404).

To prevent further issues being opened in this repo, might be worth changing the requirement to pull from their github like this:

```
pip install git+https://github.com/deepinsight/insightface.git#subdirectory=python-package
```
