### ISSUE TITLE
Import Failed 

### ISSUE THREAD

**Issue by AWMANW** [cubiq/ComfyUI_InstantID#132]
After I installed IstantID, it meet following error,how to solve it?

Traceback (most recent call last):
  File "D:\Programes\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Programes\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Programes\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import D:\Programes\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID module for custom nodes: No module named 'cv2'

Import times for custom nodes:
   0.0 seconds: D:\Programes\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\Programes\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: D:\Programes\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\Programes\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\Programes\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: D:\Programes\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds (IMPORT FAILED): D:\Programes\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.6 seconds: D:\Programes\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   7.3 seconds: D:\Programes\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

**Comment by cubiq** [comment]
you need to install opencv

**Comment by AWMANW** [comment]
I use the ComfyUI_windows_portable version, I assume every dependices are embeded.

**Comment by cubiq** [comment]
no, not really. you will also have to install insightface

**Comment by AWMANW** [comment]
Could please to instruct me how to do it?

**Comment by IntellectusPrime** [comment]
i have the same problem. everything is installed and up to date. Still import fails

**Comment by ewebgh33** [comment]
I followed the steps from @IntellectusPrime, opened ComfyUI, InstantID (native support) still won't load/import.
Uninstalled/reinstalled the custom nodes
Same problem, still red, still says can't import.

How do we solve this please?
Specifically I am trying to use in the comfyUI workflow from here:
https://github.com/fofr/cog-consistent-character?tab=readme-ov-file

**Comment by migandhi** [comment]
> I followed the steps from @IntellectusPrime, opened ComfyUI, InstantID (native support) still won't load/import. Uninstalled/reinstalled the custom nodes Same problem, still red, still says can't import.
> 
> How do we solve this please? Specifically I am trying to use in the comfyUI workflow from here: https://github.com/fofr/cog-consistent-character?tab=readme-ov-file
> 
> EDIT
> 
> This solved it for me
> 
> https://www.reddit.com/r/comfyui/comments/18ou0ly/installing_insightface/
> 
> python_embeded\python.exe -m pip uninstall insightface then download the insightface wheel for 3.11 and python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl then reboot comfy

Yes this worked for me, installing from the whl
