### ISSUE TITLE
 'ModelPatcher' object has no attribute 'get_model_object'

### ISSUE THREAD

**Issue by lancje** [cubiq/ComfyUI_InstantID#134]
Error occurred when executing ApplyInstantIDAdvanced:

'ModelPatcher' object has no attribute 'get_model_object'
I have verified my installation steps and confirmed that all required libraries and models have been correctly placed in the designated directories. I have also ensured that my ComfyUI is up to date, and all dependent libraries are at their latest versions.

**Comment by cubiq** [comment]
update this extension and comfyUI, they don't appear to be actually updated

**Comment by discoltk** [comment]
Came to report the same (had updated via manager.)  It seems @cubiq is correct, manual git pull of comfyui fixed the issue.

**Comment by lancje** [comment]
yes，I have now updated everything to the latest versions and am currently testing the application.

If I encounter any further problems or have additional questions, I will not hesitate to reach out again for assistance.
