### ISSUE TITLE
instantid workflow not working correctly for a large image

### ISSUE THREAD

**Issue by MaxTran96** [cubiq/ComfyUI_InstantID#138]
My input images are the images taken from my iphone (2kx3k) and (3kx4k). I noticed that the output of the instantid workflow sometimes dont make any sense, it doesnt even contain any person. Should i scale the input image down to 1024x1024?

**Comment by cubiq** [comment]
can you provide an image that doesn't work?

**Comment by MaxTran96** [comment]
figured it out, just missing a mask
