### ISSUE TITLE
InsightFaceLoaderIID not found

### ISSUE THREAD

**Issue by patrickas** [cubiq/ComfyUI_InstantID#14]
When I try to load the workflow instantID.json from this repo I get

" When loading the graph, the following node types were not found:
InsightFaceLoaderIID
Nodes that have failed to load will show as red on the graph. "

I made sure that insightface is installed, but still cannot find  the node InsightFaceLoaderIID.
Deleting the offending node and adding a regular "InsightFaceLoader" node seems to load... but then I get more errors so probably not it...

**Comment by JorgeR81** [comment]
You need to use the 2 workflows that are in the "examples" folder ( InstantID_default.json / InstantID_posed.json )

That one is probably from an older, experimental, version.

**Comment by cubiq** [comment]
it was a left over, please update the extension
