### ISSUE TITLE
每次打开comfyui，instantid的节点都会爆红，但是重启comfyui就能解决，很奇怪

### ISSUE THREAD

**Issue by CHENERICK1** [cubiq/ComfyUI_InstantID#140]
每次打开comfyui，instantid的节点都会爆红，但是重启comfyui就能解决，很奇怪

**Comment by cubiq** [comment]
I'm sorry I do not understand what you mean

**Comment by CHENERICK1** [comment]
Every time I turn on comfyui, instantid's nodes explode，cant be used, but restarting comfyui can solve it, which is weird ...i need ur help thanks

**Comment by Remember2015** [comment]
> Every time I turn on comfyui, instantid's nodes explode，cant be used, but restarting comfyui can solve it, which is weird ...i need ur help thanks

conflict nodes?

**Comment by cubiq** [comment]
it's impossible to say what is going on without more details, like the actual error messages. this is an installation/configuration issue anyway
