### ISSUE TITLE
image_kps causes identity loss

### ISSUE THREAD

**Issue by zhuangriyuan** [cubiq/ComfyUI_InstantID#141]
without image_kps, the input and generated image looks idetical, but with image_kps on with different head position, I think it loss about 20% identity and seems have trouble around eyes.

**Comment by cubiq** [comment]
there are so many variables. it's hard to give you a generic advice

**Comment by zhuangriyuan** [comment]
Input:
![Screenshot 2024-04-15 132343](https://github.com/cubiq/ComfyUI_InstantID/assets/48078358/bca54588-f274-43b3-b7b3-06595935a6e4)
Output:
![ComfyUI_temp_vxhzg_00002_](https://github.com/cubiq/ComfyUI_InstantID/assets/48078358/ce2df9b9-543c-4853-859c-cb73d685df6d)
Workflow:
![Screenshot 2024-04-15 132436](https://github.com/cubiq/ComfyUI_InstantID/assets/48078358/da82d612-18d2-4886-9c65-93ae7cb6355a)

**Comment by cubiq** [comment]
the face is too small, after the generation you need to upscale the face and apply the instantid again. there's a workflow in my discord for that
