### ISSUE TITLE
Error occurred when executing ApplyInstantID:  'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by CanlysXie** [cubiq/ComfyUI_InstantID#145]
help me,i dont solve this problem
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/106568288/0b71d4cc-4105-4881-9406-762051603ab0)

**Comment by cubiq** [comment]
you are probably using the wrong models, but it's impossible to say with the little info provided

**Comment by CanlysXie** [comment]
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/106568288/975bbf33-85c2-45e5-8b1e-580bba3ff8f9)
here is my model and your basic workflow @cubiq

**Comment by CanlysXie** [comment]
I solved this problem thanks to the controlnet model, thanks for your help,

**Comment by mxgjjp** [comment]
我也遇到了同样的问题，这个要如何解决请告诉一下，谢谢。

**Comment by tongtianta1** [comment]
I met the same problem, can you tell me how you solved it

**Comment by tongtianta1** [comment]
> I solved this problem thanks to the controlnet model, thanks for your help,多亏了控制网模型，我解决了这个问题，谢谢你的帮助，

Can you tell me how you solved it? Is the above model used incorrectly？

**Comment by tongtianta1** [comment]
Oh, I fixed it. It's the controlnet model, thanks！

**Comment by cyber3px** [comment]
I used this one and it seems to work, not sure why there are different ones: https://huggingface.co/InstantX/InstantID/blob/main/ControlNetModel/diffusion_pytorch_model.safetensors
