### ISSUE TITLE
Unable to use Canny preprocessor- control_v11p_sd15_canny

### ISSUE THREAD

**Issue by anandw007** [cubiq/ComfyUI_InstantID#146]
I am using ComfyUI to use InstantID, whenever I change the preprocessor from diffusion-pytorch-model-fp16 to control_v11p_sd15_canny; I am running ComyUI on a VM.

I used to use control_v11p_sd15_canny on A1111, trying to use the same workflow on ComfyUI. Getting an error when I change to control_v11p_sd15_canny.

**Comment by cubiq** [comment]
you are using the wrong controlnet. you need to pick the SDXL one

**Comment by anandw007** [comment]
Thanks @cubiq! Will try it out.
