### ISSUE TITLE
Issue with Load InstantID Model node

### ISSUE THREAD

**Issue by pointave** [cubiq/ComfyUI_InstantID#15]
The correct file path for the Ip-adapter.bin is comfyui/models/instantid, but in comfyui the node says null and undefined. I'm not using the portable version but I see someone else that is and is experiencing same issue where the model isnt being detected but is in the correct location.  
The error I get is
" Prompt outputs failed validation
InstantIDModelLoader:
    - Required input is missing: instantid_file"

**Comment by pointave** [comment]
https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Flunq9a6wu2ic1.png%3Fwidth%3D1321%26format%3Dpng%26auto%3Dwebp%26s%3Dda0d042ff2a1bfd1f73baae08598c22a30eece59

**Comment by pointave** [comment]
fixed by adding "instantid" and the file path to the extra_models.yaml

**Comment by HSJDZNM** [comment]
instantID: /home/hk/ComfyUI/custom_nodes/ComfyUI_InstantID/checkpoints/。是这样加吗？

**Comment by giusparsifal** [comment]
Hello, I have the same problem but I've not understood how you fixed it. I'm a newbie so plsCould you explain me? I tried to edit extra_model but I don't know tha path as I can't find it on A1111 directory too...

**Comment by giusparsifal** [comment]
Hello, I'm a newbie and I can't understand how you fix it. In extra_model there is already the path to controlnet models but still I can't figured it out how to fix...
Thanks

**Comment by 9527pluto** [comment]
hello , how to fix it?
thanks.

**Comment by CoUIfy** [comment]
> instantid

Interesting.
But did you have to add insightface aswell as a line?

**Comment by xiaoahuaya** [comment]
find extensions/sd-webui-comfyui/ComfyUI/folder_paths.py

![image](https://github.com/user-attachments/assets/28835c0c-d685-4345-89c9-4bd3d3837a20)

then create floder ComfyUI\models\instantid\  
add model to ComfyUI\models\instantid\  
![image](https://github.com/user-attachments/assets/bec2fffc-9fc9-4cb2-a7bb-7453555d929e)
