### ISSUE TITLE
Encountered an error message. about（'CrossAttentionPatch' object has no attribute 'add'）

### ISSUE THREAD

**Issue by ThinkpeachQ** [cubiq/ComfyUI_InstantID#155]
Error occurred when executing ApplyInstantID:

'CrossAttentionPatch' object has no attribute 'add'

File "F:\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "F:\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 353, in apply_instantid
_set_model_patch_replace(work_model, patch_kwargs, ("input", id, index))
File "F:\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 136, in _set_model_patch_replace
to["patches_replace"]["attn2"][key].add(instantid_attention, **patch_kwargs)

![image](https://github.com/cubiq/ComfyUI_InstantID/assets/133643364/dff984fc-1b22-49e8-b368-55c5eadd4ca9)
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/133643364/420b8a2e-8a63-45dd-9fa3-d1e160a8f3ec)
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/133643364/502e8434-5fc8-4aa4-be3b-87c96451ec26)
The files required for instantID are all in their respective locations

**Comment by guopei6** [comment]
mee too

**Comment by cubiq** [comment]
upgrade any of the following that you have installed: ipadapter, pulid and instantid

**Comment by songnan1111** [comment]
Is the problem solved? My mistake is exactly the same as yours
![Uploading 20240523-141802.jpg…]()

**Comment by songnan1111** [comment]
![20240523-141802](https://github.com/cubiq/ComfyUI_InstantID/assets/132810633/5e9b6ffa-84f6-4bed-a640-659de42b90d4)
Is the problem solved? My mistake is exactly the same as yours

**Comment by cubiq** [comment]
yes you need to update ipadapter, pulid and instantid (if they are installed)
