### ISSUE TITLE
Can you help me with this issue, please? instantID error 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by Zkk19492024** [cubiq/ComfyUI_InstantID#158]
When I first installed it, it worked fine, but after a few days, it reported an error, I don't know what happened. I don't know what's going on. Thank you very much, it's been bothering me for a long time and I can't solve it.
!!! Exception during processing!!! 'NoneType' object has no attribute 'copy'
Traceback (most recent call last):
  File "D:\ComfyUI_01\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_01\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_01\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_01\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 383, in apply_instantid
    c_net = control_net.copy().set_cond_hint(face_kps.movedim(-1,1), cn_strength, (start_at, end_at))
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by cubiq** [comment]
post a minimal workflow that causes this issue

**Comment by Zkk19492024** [comment]
Just solved it, downloaded a new controlnet model and replaced it, thanks to the author for replying, thanks!
