### ISSUE TITLE
Using instantid almost 6 times slower than normal generation

### ISSUE THREAD

**Issue by patientx** [cubiq/ComfyUI_InstantID#16]
I am on amd (rx 6600 8gb) on windows , normally with sdxl I get 10sec/it which I am cool with. I have to use CPU for face analysis , and that makes the average step around 60 secs on the same workflow. I can see that my gpu is doing nothing almost all the time except a few seconds (probably the actual generating). Is there a way to speed this up at all ?

**Comment by fishkingsin** [comment]
I ma new to here too
please share your config, curious  the sampler config is different from ordinary 
<img width="600" alt="Screenshot 2024-02-14 at 12 09 43 AM" src="https://github.com/cubiq/ComfyUI_InstantID/assets/481343/0d04404c-9208-4793-8787-d7e0b85575ee">

**Comment by patientx** [comment]
I am using a turbo model (ultraspiceXLturbo , so using cfg 2, sampler dpmpp_2m_sde. These are recomended by that model's creator. They also recommend 7 to 11 steps so using 7 steps as well...

Now I tried rocm , it seems to be working but no speed change so I am not sure if it really does.

**Comment by cubiq** [comment]
face analysis should be relatively fast on CPU, upgrade protobuf if it's slow.

please note that the face analysis should be always kept on the CPU anyway, it's a waste of resources to use the GPU for that.

**Comment by patientx** [comment]
> face analysis should be relatively fast on CPU, upgrade protobuf if it's slow.
> 
> please note that the face analysis should be always kept on the CPU anyway, it's a waste of resources to use the GPU for that.

Using CPU always, (tried ROCM one time only) Updated protobuf as you suggested but gen time is same or worse most of the time. Keep in mind I am using --lowvram option and that is probably using swap file extensively. SDXL itself already kills the generation performance (from 1.7 sec/it to 10 sec/it) but the need to use both huge models (for me like a 1.5 model in total) crashes it completely. If it was possible maybe using smaller models would help , what do you think ? (can we get pruned versions of that ipadapter and controlnet models if so)

**Comment by cubiq** [comment]
I guess the main problem is directml that is really bad. If you are on AMD I highly recommend using linux

**Comment by patientx** [comment]
I know all about directml problems on windows. Using linux just for this is not practical for me. It is just a hobby, wanted to know if it was possible to get pruned versions something tells me it would help a lot for my situation. Thanks for your hardwork on the nodes.

**Comment by cubiq** [comment]
if this technology gets used more I'm sure we will see more models coming out, hopefully with less memory requirement

**Comment by aphexetwine** [comment]
Same issue on Mac M1 Pro 16gb... SDXL generation takes around 6s/it, InstantID takes 240s/it. Tried different settings too.
