### ISSUE TITLE
(IMPORT FAILED) ComfyUI InstantID (Native Support)

### ISSUE THREAD

**Issue by BinglunWang** [cubiq/ComfyUI_InstantID#161]
Hi,

I'm writing to ask a solution for import failed issue for comfyUI InstantID. I tried to install comfyUI InstantID by git clone and comfyUI manager. But it still does not work.

Here's my device and environment information for your convenience:

- system: Ubuntu 22.04.4 LTS
- comfyui version: ComfyUI: 2199[83d969](2024-05-21) Manager: V2.34.1

Thank you so much in advance!

**Comment by cubiq** [comment]
without an error message it's impossible to say. probably insightface failed to install

**Comment by BinglunWang** [comment]
![Screenshot from 2024-05-22 18-41-10](https://github.com/cubiq/ComfyUI_InstantID/assets/43243214/d29ade83-715c-4d13-8651-523b7b614766)

Thanks for your reply. Here's my screenshot

**Comment by cubiq** [comment]
that unfortunately doesn't tell us much, we need the actual error message from the console

**Comment by BinglunWang** [comment]
> that unfortunately doesn't tell us much, we need the actual error message from the console

Thanks. May I know how to get error messages from the console.

If it's use "queue prompt", The above figure may be the all error message I have. 
Because I cannot use any InstantID nodes (e.g. instant ID) as I cannot import InstantID .

Another examples: I tried to load from a created workflow are these:
![Screenshot from 2024-05-22 19-14-30](https://github.com/cubiq/ComfyUI_InstantID/assets/43243214/2c2673cf-59fe-4854-836d-6bdd63d73b77)

additional information: I tried update comfyUI version before I use it

**Comment by cubiq** [comment]
we the the actual backtrace from the terminal window

**Comment by BinglunWang** [comment]
I see. Thanks!

Here's the error when I try to fix instant ID in comfyUI:

`## ComfyUI-Manager: EXECUTE => ['/home/bingwang/miniconda3/envs/SD_render/bin/python', '-m', 'pip', 'install', 'insightface']
 Collecting insightface
   Using cached insightface-0.7.3.tar.gz (439 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'done'
   Installing backend dependencies: started
   Installing backend dependencies: finished with status 'done'
   Preparing metadata (pyproject.toml): started
   Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting onnx (from insightface)
   Using cached onnx-1.16.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (16 kB)
        Collecting easydict (from insightface)
   Using cached easydict-1.13-py3-none-any.whl.metadata (4.2 kB)
 Collecting cython (from insightface)
   Using cached Cython-3.0.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
  Collecting prettytable (from insightface)
   Using cached prettytable-3.10.0-py3-none-any.whl.metadata (30 kB)
                           Using cached Cython-3.0.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
 Using cached easydict-1.13-py3-none-any.whl (6.8 kB)
 Using cached onnx-1.16.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
 Using cached prettytable-3.10.0-py3-none-any.whl (28 kB)
 Building wheels for collected packages: insightface
   Building wheel for insightface (pyproject.toml): started
   Building wheel for insightface (pyproject.toml): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]   
[!]   × Building wheel for insightface (pyproject.toml) did not run successfully.
[!]   │ exit code: 1
[!]   ╰─> [223 lines of output]
[!]       WARNING: pandoc not enabled
[!]       running bdist_wheel
[!]       running build
[!]       running build_py
[!]       creating build
[!]       creating build/lib.linux-x86_64-cpython-310
[!]       creating build/lib.linux-x86_64-cpython-310/insightface
[!]       copying insightface/__init__.py -> build/lib.linux-x86_64-cpython-310/insightface
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/app
[!]       copying insightface/app/face_analysis.py -> build/lib.linux-x86_64-cpython-310/insightface/app
[!]       copying insightface/app/mask_renderer.py -> build/lib.linux-x86_64-cpython-310/insightface/app
[!]       copying insightface/app/common.py -> build/lib.linux-x86_64-cpython-310/insightface/app
[!]       copying insightface/app/__init__.py -> build/lib.linux-x86_64-cpython-310/insightface/app
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/model_zoo
[!]       copying insightface/model_zoo/model_store.py -> build/lib.linux-x86_64-cpython-310/insightface/model_zoo
[!]       copying insightface/model_zoo/model_zoo.py -> build/lib.linux-x86_64-cpython-310/insightface/model_zoo
[!]       copying insightface/model_zoo/scrfd.py -> build/lib.linux-x86_64-cpython-310/insightface/model_zoo
[!]       copying insightface/model_zoo/inswapper.py -> build/lib.linux-x86_64-cpython-310/insightface/model_zoo
[!]       copying insightface/model_zoo/attribute.py -> build/lib.linux-x86_64-cpython-310/insightface/model_zoo
[!]       copying insightface/model_zoo/arcface_onnx.py -> build/lib.linux-x86_64-cpython-310/insightface/model_zoo
[!]       copying insightface/model_zoo/__init__.py -> build/lib.linux-x86_64-cpython-310/insightface/model_zoo
 Failed to build insightface
[!]       copying insightface/model_zoo/landmark.py -> build/lib.linux-x86_64-cpython-310/insightface/model_zoo
[!]       copying insightface/model_zoo/retinaface.py -> build/lib.linux-x86_64-cpython-310/insightface/model_zoo
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/data
[!]       copying insightface/data/rec_builder.py -> build/lib.linux-x86_64-cpython-310/insightface/data
[!]       copying insightface/data/pickle_object.py -> build/lib.linux-x86_64-cpython-310/insightface/data
[!]       copying insightface/data/image.py -> build/lib.linux-x86_64-cpython-310/insightface/data
[!]       copying insightface/data/__init__.py -> build/lib.linux-x86_64-cpython-310/insightface/data
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/utils
[!]       copying insightface/utils/download.py -> build/lib.linux-x86_64-cpython-310/insightface/utils
[!]       copying insightface/utils/face_align.py -> build/lib.linux-x86_64-cpython-310/insightface/utils
[!]       copying insightface/utils/filesystem.py -> build/lib.linux-x86_64-cpython-310/insightface/utils
[!]       copying insightface/utils/constant.py -> build/lib.linux-x86_64-cpython-310/insightface/utils
[!]       copying insightface/utils/storage.py -> build/lib.linux-x86_64-cpython-310/insightface/utils
[!]       copying insightface/utils/__init__.py -> build/lib.linux-x86_64-cpython-310/insightface/utils
[!]       copying insightface/utils/transform.py -> build/lib.linux-x86_64-cpython-310/insightface/utils
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/thirdparty
[!]       copying insightface/thirdparty/__init__.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/commands
[!]       copying insightface/commands/rec_add_mask_param.py -> build/lib.linux-x86_64-cpython-310/insightface/commands
[!]       copying insightface/commands/insightface_cli.py -> build/lib.linux-x86_64-cpython-310/insightface/commands
[!]       copying insightface/commands/__init__.py -> build/lib.linux-x86_64-cpython-310/insightface/commands
[!]       copying insightface/commands/model_download.py -> build/lib.linux-x86_64-cpython-310/insightface/commands
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d
[!]       copying insightface/thirdparty/face3d/__init__.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh_numpy
[!]       copying insightface/thirdparty/face3d/mesh_numpy/render.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh_numpy
[!]       copying insightface/thirdparty/face3d/mesh_numpy/light.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh_numpy
[!]       copying insightface/thirdparty/face3d/mesh_numpy/io.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh_numpy
[!]       copying insightface/thirdparty/face3d/mesh_numpy/vis.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh_numpy
[!]       copying insightface/thirdparty/face3d/mesh_numpy/__init__.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh_numpy
[!]       copying insightface/thirdparty/face3d/mesh_numpy/transform.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh_numpy
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/morphable_model
[!]       copying insightface/thirdparty/face3d/morphable_model/morphabel_model.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/morphable_model
[!]       copying insightface/thirdparty/face3d/morphable_model/load.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/morphable_model
[!]       copying insightface/thirdparty/face3d/morphable_model/fit.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/morphable_model
[!]       copying insightface/thirdparty/face3d/morphable_model/__init__.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/morphable_model
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh
[!]       copying insightface/thirdparty/face3d/mesh/render.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh
[!]       copying insightface/thirdparty/face3d/mesh/light.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh
[!]       copying insightface/thirdparty/face3d/mesh/io.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh
[!]       copying insightface/thirdparty/face3d/mesh/vis.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh
[!]       copying insightface/thirdparty/face3d/mesh/__init__.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh
[!]       copying insightface/thirdparty/face3d/mesh/transform.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh
[!]       running egg_info
[!]       writing insightface.egg-info/PKG-INFO
[!]       writing dependency_links to insightface.egg-info/dependency_links.txt
[!]       writing entry points to insightface.egg-info/entry_points.txt
[!]       writing requirements to insightface.egg-info/requires.txt
[!]       writing top-level names to insightface.egg-info/top_level.txt
[!]       reading manifest file 'insightface.egg-info/SOURCES.txt'
[!]       writing manifest file 'insightface.egg-info/SOURCES.txt'
[!]       /tmp/pip-build-env-mi53k9zi/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py:207: _Warning: Package 'insightface.data.images' is absent from the `packages` configuration.
[!]       !!
[!]       
[!]               ********************************************************************************
[!]               ############################
[!]               # Package would be ignored #
[!]               ############################
[!]               Python recognizes 'insightface.data.images' as an importable package[^1],
[!]               but it is absent from setuptools' `packages` configuration.
[!]       
[!]               This leads to an ambiguous overall configuration. If you want to distribute this
[!]               package, please make sure that 'insightface.data.images' is explicitly added
[!]               to the `packages` configuration field.
[!]       
[!]               Alternatively, you can also rely on setuptools' discovery methods
[!]               (for example by using `find_namespace_packages(...)`/`find_namespace:`
[!]               instead of `find_packages(...)`/`find:`).
[!]       
[!]               You can read more about "package discovery" on setuptools documentation page:
[!]       
[!]               - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
[!]       
[!]               If you don't want 'insightface.data.images' to be distributed and are
[!]               already explicitly excluding 'insightface.data.images' via
[!]               `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
[!]               you can try to use `exclude_package_data`, or `include-package-data=False` in
[!]               combination with a more fine grained `package-data` configuration.
[!]       
[!]               You can read more about "package data files" on setuptools documentation page:
[!]       
[!]               - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
[!]       
[!]       
[!]               [^1]: For Python, any directory (with suitable naming) can be imported,
[!]                     even if it does not contain any `.py` files.
[!]                     On the other hand, currently there is no concept of package data
[!]                     directory, all directories are treated like packages.
[!]               ********************************************************************************
[!]       
[!]       !!
[!]         check.warn(importable)
[!]       /tmp/pip-build-env-mi53k9zi/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py:207: _Warning: Package 'insightface.data.objects' is absent from the `packages` configuration.
[!]       !!
[!]       
[!]               ********************************************************************************
[!]               ############################
[!]               # Package would be ignored #
[!]               ############################
[!]               Python recognizes 'insightface.data.objects' as an importable package[^1],
[!]               but it is absent from setuptools' `packages` configuration.
[!]       
[!]               This leads to an ambiguous overall configuration. If you want to distribute this
[!]               package, please make sure that 'insightface.data.objects' is explicitly added
[!]               to the `packages` configuration field.
[!]       
[!]               Alternatively, you can also rely on setuptools' discovery methods
[!]               (for example by using `find_namespace_packages(...)`/`find_namespace:`
[!]               instead of `find_packages(...)`/`find:`).
[!]       
[!]               You can read more about "package discovery" on setuptools documentation page:
[!]       
[!]               - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
[!]       
[!]               If you don't want 'insightface.data.objects' to be distributed and are
[!]               already explicitly excluding 'insightface.data.objects' via
[!]               `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
[!]               you can try to use `exclude_package_data`, or `include-package-data=False` in
[!]               combination with a more fine grained `package-data` configuration.
[!]       
[!]               You can read more about "package data files" on setuptools documentation page:
[!]       
[!]               - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
[!]       
[!]       
[!]               [^1]: For Python, any directory (with suitable naming) can be imported,
[!]                     even if it does not contain any `.py` files.
[!]                     On the other hand, currently there is no concept of package data
[!]                     directory, all directories are treated like packages.
[!]               ********************************************************************************
[!]       
[!]       !!
[!]         check.warn(importable)
[!]       /tmp/pip-build-env-mi53k9zi/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py:207: _Warning: Package 'insightface.thirdparty.face3d.mesh.cython' is absent from the `packages` configuration.
[!]       !!
[!]       
[!]               ********************************************************************************
[!]               ############################
[!]               # Package would be ignored #
[!]               ############################
[!]               Python recognizes 'insightface.thirdparty.face3d.mesh.cython' as an importable package[^1],
[!]               but it is absent from setuptools' `packages` configuration.
[!]       
[!]               This leads to an ambiguous overall configuration. If you want to distribute this
[!]               package, please make sure that 'insightface.thirdparty.face3d.mesh.cython' is explicitly added
[!]               to the `packages` configuration field.
[!]       
[!]               Alternatively, you can also rely on setuptools' discovery methods
[!]               (for example by using `find_namespace_packages(...)`/`find_namespace:`
[!]               instead of `find_packages(...)`/`find:`).
[!]       
[!]               You can read more about "package discovery" on setuptools documentation page:
[!]       
[!]               - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
[!]       
[!]               If you don't want 'insightface.thirdparty.face3d.mesh.cython' to be distributed and are
[!]               already explicitly excluding 'insightface.thirdparty.face3d.mesh.cython' via
[!]               `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
[!]               you can try to use `exclude_package_data`, or `include-package-data=False` in
[!]               combination with a more fine grained `package-data` configuration.
[!]       
[!]               You can read more about "package data files" on setuptools documentation page:
[!]       
[!]               - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
[!]       
[!]       
[!]               [^1]: For Python, any directory (with suitable naming) can be imported,
[!]                     even if it does not contain any `.py` files.
[!]                     On the other hand, currently there is no concept of package data
[!]                     directory, all directories are treated like packages.
[!]               ********************************************************************************
[!]       
[!]       !!
[!]         check.warn(importable)
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/data/images
[!]       copying insightface/data/images/Tom_Hanks_54745.png -> build/lib.linux-x86_64-cpython-310/insightface/data/images
[!]       copying insightface/data/images/mask_black.jpg -> build/lib.linux-x86_64-cpython-310/insightface/data/images
[!]       copying insightface/data/images/mask_blue.jpg -> build/lib.linux-x86_64-cpython-310/insightface/data/images
[!]       copying insightface/data/images/mask_green.jpg -> build/lib.linux-x86_64-cpython-310/insightface/data/images
[!]       copying insightface/data/images/mask_white.jpg -> build/lib.linux-x86_64-cpython-310/insightface/data/images
[!]       copying insightface/data/images/t1.jpg -> build/lib.linux-x86_64-cpython-310/insightface/data/images
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/data/objects
[!]       copying insightface/data/objects/meanshape_68.pkl -> build/lib.linux-x86_64-cpython-310/insightface/data/objects
[!]       creating build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh/cython
[!]       copying insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh/cython
[!]       copying insightface/thirdparty/face3d/mesh/cython/mesh_core.h -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh/cython
[!]       copying insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.c -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh/cython
[!]       copying insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh/cython
[!]       copying insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.pyx -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh/cython
[!]       copying insightface/thirdparty/face3d/mesh/cython/setup.py -> build/lib.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh/cython
[!]       running build_ext
[!]       building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
[!]       creating build/temp.linux-x86_64-cpython-310
[!]       creating build/temp.linux-x86_64-cpython-310/insightface
[!]       creating build/temp.linux-x86_64-cpython-310/insightface/thirdparty
[!]       creating build/temp.linux-x86_64-cpython-310/insightface/thirdparty/face3d
[!]       creating build/temp.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh
[!]       creating build/temp.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh/cython
[!]       gcc -pthread -B /home/bingwang/miniconda3/envs/SD_render/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/bingwang/miniconda3/envs/SD_render/include -fPIC -O2 -isystem /home/bingwang/miniconda3/envs/SD_render/include -fPIC -Iinsightface/thirdparty/face3d/mesh/cython -I/tmp/pip-build-env-mi53k9zi/overlay/lib/python3.10/site-packages/numpy/core/include -I/home/bingwang/miniconda3/envs/SD_render/include/python3.10 -c insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp -o build/temp.linux-x86_64-cpython-310/insightface/thirdparty/face3d/mesh/cython/mesh_core.o
[!]       gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
[!]       compilation terminated.
[!]       error: command '/usr/bin/gcc' failed with exit code 1
[!]       [end of output]
[!]   
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!]   ERROR: Failed building wheel for insightface
[!] ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects
install script failed: https://github.com/cubiq/ComfyUI_InstantID

## ComfyUI-Manager: EXECUTE => ['/home/bingwang/miniconda3/envs/SD_render/bin/python', '-m', 'pip', 'install', 'onnxruntime']
         
## ComfyUI-Manager: EXECUTE => ['/home/bingwang/miniconda3/envs/SD_render/bin/python', '-m', 'pip', 'install', 'onnxruntime-gpu']
         Attempt to fixing '['https://github.com/cubiq/ComfyUI_InstantID']' is done.
After restarting ComfyUI, please refresh the browser.
FETCH DATA from: /home/bingwang/Documents/GitHub/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1514988643_custom-node-list.json [DONE]
FETCH DATA from: /home/bingwang/Documents/GitHub/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/746607195_github-stats.json [DONE]
FETCH DATA from: /home/bingwang/Documents/GitHub/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json [DONE]`

**Comment by cubiq** [comment]
your pc was not able to build the dependency, it's hard to say what is missing, maybe the build-essentials since you are on ubuntu

**Comment by BinglunWang** [comment]
Thank you for your reply. That's a pity.

Shall I close this issue or keep open?

**Comment by cubiq** [comment]
you can install the missing dependencies with `apt install build-essential`

**Comment by BinglunWang** [comment]
I tried `sudo apt install build-essential`. But seems it's already a newest version.

`build-essential is already the newest version (12.9ubuntu3).
The following packages were automatically installed and are no longer required:
  libnvidia-container-tools libnvidia-container1
Use 'sudo apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 47 not to upgrade.
`

**Comment by Laisvydas3030** [comment]
same problem on Windows

**Comment by BinglunWang** [comment]
> same problem on Windows

Can you also provide the details?

**Comment by freakAccidentPickle** [comment]
Same problem here on windows. 

Error says 

Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 13, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID module for custom nodes: No module named 'insightface'

**Comment by freakAccidentCrustacean** [comment]
Add the same problem on windows, for anyone else seeing this. CMD error was that insightface was missing.

Used this instruction from reddit and it fixed the problem :

From the ComfyUI root folder (where you have "webui-user.bat" file) check the version of Python aka run CMD and type "python_embeded\python.exe -V"

Depending on Python version (3.10 or 3.11) download prebuilt Insightface package to ComfyUI root folder:
Python 3.10: https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl
Python 3.11: https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl

Install latest pip version: "python_embeded\python.exe -m pip install -U pip"

Install Insightface:
Python 3.10: "python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl"
Python 3.11: "python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl

**Comment by HydraBucket** [comment]
> Had the same problem on windows, for anyone else seeing this. CMD error was that insightface was missing.
> 
> Used this instruction from reddit and it fixed the problem :
> 
> From the ComfyUI root folder (where you have "webui-user.bat" file) check the version of Python aka run CMD and type "python_embeded\python.exe -V"
> 
> Depending on Python version (3.10 or 3.11) download prebuilt Insightface package to ComfyUI root folder: Python 3.10: https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl Python 3.11: https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl
> 
> Install latest pip version: "python_embeded\python.exe -m pip install -U pip"
> 
> Install Insightface: Python 3.10: "python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl" Python 3.11: "python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl

Youre a legend. This fixed my issue.

**Comment by Chinnzzz** [comment]
> 在 Windows 上也遇到了同样的问题，其他人也看到了这个问题。CMD 错误是缺少 insightface。
> 
> 使用 reddit 上的这个说明并解决了该问题：
> 
> 从 ComfyUI 根文件夹（其中有“webui-user.bat”文件）检查 Python 的版本，即运行 CMD 并输入“python_embeded\python.exe -V”
> 
> 根据 Python 版本（3.10 或 3.11）将预构建的 Insightface 包下载到 ComfyUI 根文件夹： Python 3.10： https: [//github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl) Python 3.11：https: [//github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl)
> 
> 安装最新的 pip 版本：“python_embeded\python.exe -m pip install -U pip”
> 
> 安装 Insightface： Python 3.10：“python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl” Python 3.11：“python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl

wow,niu b,bro.fixed my issue

**Comment by AaronGuo47** [comment]
> Had the same problem on windows, for anyone else seeing this. CMD error was that insightface was missing.
> 
> Used this instruction from reddit and it fixed the problem :
> 
> From the ComfyUI root folder (where you have "webui-user.bat" file) check the version of Python aka run CMD and type "python_embeded\python.exe -V"
> 
> Depending on Python version (3.10 or 3.11) download prebuilt Insightface package to ComfyUI root folder: Python 3.10: https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl Python 3.11: https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl
> 
> Install latest pip version: "python_embeded\python.exe -m pip install -U pip"
> 
> Install Insightface: Python 3.10: "python_embeded\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl" Python 3.11: "python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl


After this step I couldn't even start ComfyUI. The cmd window just gives me this:

Traceback (most recent call last):
  File "D:\Work\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\main.py", line 261, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 654, in run_until_complete
  File "D:\Work\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\main.py", line 166, in run
    await asyncio.gather(server.start_multi_address(addresses, call_on_start), server.publish_loop())
  File "D:\Work\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\server.py", line 838, in start_multi_address
    await site.start()
  File "D:\Work\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\base_events.py", line 1536, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): only one usage of each socket address (protocol/network address/port) is normally permitted
