### ISSUE TITLE
Why do I end up with a dotted line around my face when I use a mask to redraw my face in instantID?

### ISSUE THREAD

**Issue by sebord** [cubiq/ComfyUI_InstantID#166]
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/104607562/bb6030d2-d59a-4bd5-82ca-6f33eb387926)
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/104607562/445cd7fc-bc04-4fc9-8883-9e0d470d581d)

**Comment by cubiq** [comment]
you need to expand the mask a little
