### ISSUE TITLE
"Doesn't use diffusers" but then error on basic workflow that was only solved by adding the diffusers safetensors model

### ISSUE THREAD

**Issue by ewebgh33** [cubiq/ComfyUI_InstantID#168]
As the title says
I am confused
Do we need the safetensors model or not?
Loaded the basic workflow
It failed, said I was missing the model
Added the diffusers safetensors model, it works
So
It DOES use diffusers safetensors? What am I missing here, the readme says right at the top, doesn't use diffusers, is different.

**Comment by ewebgh33** [comment]
Maybe I'm confused because the model's full filename is
`diffusion_pytorch_model.safetensors`

Maybe this is a language thing
I mean, I solved my problem by installing that model so, cool
But
The readme says _"This extension differs from the many already available as it doesn't use diffusers but instead implements InstantID natively and it fully integrates with ComfyUI."_
But then you have to install a safetensors file whose filename is literally "_diffusers_"
Sorry for the confusion?

**Comment by cubiq** [comment]
the filename literally says _diffusion_ not _diffusers_ . Diffusers is library not a file. Ask chatgpt I'm sure it's able to explain it very quickly

**Comment by ewebgh33** [comment]
Ah OK got it, got it. :) 
It is a language thing
Many words, many languages in my head
Thank you
