### ISSUE TITLE
Bypassing the InstantID nodes in the workflow leads to washed-out and corrupted generations

### ISSUE THREAD

**Issue by LuLmaster69** [cubiq/ComfyUI_InstantID#17]
I've found that if you bypass these nodes inside your workflow while they are connected to the ksampler it leads to washed-out color and corruptions in generation.

When the nodes are enabled or if they are completely removed (or disconnected from other nodes) the quality is the same as per usual image generation. The corruption only starts to appear when the nodes are bypassed while connected to ksampler.

bypassed nodes in the workflow
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/145214785/c9b16c72-f450-4c94-9412-e869c88bf50e)

the result with bypassed nodes
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/145214785/a174e5ed-4467-446f-bcde-0d48535525fa)

the result with removed (disconnected nodes)
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/145214785/f624c8eb-7e44-49e2-a2d7-8a26f51a4604)

**Comment by cubiq** [comment]
upgrade the extension, only bypass the InstantID node and the Controlnet.
