### ISSUE TITLE
Can someone explain to me the different json files? (InstantID_multi id, depth, ipadaptro, basic) etc

### ISSUE THREAD

**Issue by CoUIfy** [cubiq/ComfyUI_InstantID#170]
Hi, I am trying to understand what they do exalcty and how to use them?

- Basic: 
You can use direclty ONE image with a face and you insert a prompt and model. OK
- MultiID:
I noticed there was 2 FACE images and a third image.
I am still not sure what I should do or the best config, if I insert a face in the third image, (which is not croped), I obtain strange imamges where there are 2 or more bodies in a single image.. I suppose that image is for style or something? What if I insert 2 differnet faces? 
Tell me more about how best to use it.
- Depth:
only one image is face, the other can by anything. How best to use this?
- Idaptor IP:
Pretty understandable.

Summary: I dont undertand the nodes in MultiID, and I dont find a good use for depth, if you have any examples

**Comment by cubiq** [comment]
I think this video explains pretty much everything https://youtu.be/wMLiGhogOPE
