### ISSUE TITLE
It seems not to work with cosxl model, is there any walk around solution?

### ISSUE THREAD

**Issue by Remember2015** [cubiq/ComfyUI_InstantID#181]
This plugin works correctly with SDXL model, but not works if CosXL model used. 
Is this expected?

**Comment by cubiq** [comment]
not really trained for that, but I think I could make it work... but you'd need a lot of vram. what error do you get?

**Comment by Remember2015** [comment]
> not really trained for that, but I think I could make it work... but you'd need a lot of vram. what error do you get?

workflow run successfully with no errors, but face from input image had no effect on the output image

**Comment by cubiq** [comment]
they are just not trained for it
