### ISSUE TITLE
please confirm where to put all the extra files - my Instant-ID won't load properly

### ISSUE THREAD

**Issue by MokkaBoss1** [cubiq/ComfyUI_InstantID#19]
![New Project](https://github.com/cubiq/ComfyUI_InstantID/assets/136205220/2e272a79-f421-4118-9fba-61686841a353)

Is this correct?

**Comment by cubiq** [comment]
please read the readme file, you find all the locations there

**Comment by MokkaBoss1** [comment]
Hi, the readme file is the same text which is included in the main github
page. I tried with limited knowledge and skill to follow it.

It mentions I need to add insightface to my libraries along
with `onnxruntime` and `onnxruntime-gpu`. Do I need to download these 2
extra?

Regards

Mokkaboss1

**Comment by JorgeR81** [comment]
You also need to install insightface.

I installed InsightFace successfully, with these instructions:
https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#troubleshooting

There is also a video:
https://www.youtube.com/watch?v=vCCVxGtCyho

Once you have Insightface, you will also be able to use other custom nodes, that require it, like FaceID ( IPAdapter_plus )

More info here:
https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#faceid
cubiq/ComfyUI_IPAdapter_plus#162

**Comment by SoutPark99** [comment]
> You also need to install insightface.
> 
> I installed InsightFace successfully, with these instructions: https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#troubleshooting
> 
> There is also a video: https://www.youtube.com/watch?v=vCCVxGtCyho
> 
> Once you have Insightface, you will also be able to use other custom nodes, that require it, like FaceID ( IPAdapter_plus )
> 
> More info here: https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#faceid [cubiq/ComfyUI_IPAdapter_plus#162](https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162)

Wow! So you're reply **really** needs to be added to the front page. I was stuck on this step for hours. The Cubiq version is now loaded on through Comfy Manager but I think there is something still wrong with it. It would absolutely refuse to recognized the ip-adapter. When I reinstalled through git clone, it ran perfect the first time. 

Can we please have a visual examples of how the multi_id and depth workflow could be used? Coming from Automatic1111 I'm newish to Comfy and this is a lot to take in. I've used InstantID with ControlNet 1,2, and 3 when I really had to force the model to get a complicated pose/action. But you can only get like 5-6 gens in before it crashes.

Thanks again for posting all of this!

**Comment by hotlml** [comment]
> ![New Project](https://private-user-images.githubusercontent.com/136205220/304536492-2e272a79-f421-4118-9fba-61686841a353.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNzcxNTgsIm5iZiI6MTcwODA3Njg1OCwicGF0aCI6Ii8xMzYyMDUyMjAvMzA0NTM2NDkyLTJlMjcyYTc5LWY0MjEtNDExOC05ZmJhLTYxNjg2ODQxYTM1My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQwOTQ3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2YzYzcxZThmMjQwMzcyYjBiZTU2OTRkMWFjYjQwN2ViOTBkMWUxN2IwNjFiMTY2Y2ExNTEwNmU0MTBlNTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WHv-0_yhpz-AXz-kPzdDa1gZCAN0GV1javGeSMCUxlA)
> 
> Is this correct?


Hi ,

I'm having trouble running my model because the files are not in the correct folders. Could you please share a screenshot of your file structure so I can see how you have it organized?
