### ISSUE TITLE
执行 ApplyInstantIDAdvanced 时出错：  “CrossAttentionPatch”对象没有属性“add”  文件“D：\ComfyUI-aki-v1.3\execution.py”，第 151 行，recursive_execute output_data，output_ui = get_output_data（obj， input_data_all） 文件“D：\ComfyUI-aki-v1.3\execution.py”，第 81 行，get_output_data return_values = map_node_over_list（obj， input_data_all， obj.函数，allow_interrupt=True） 文件“D：\ComfyUI-aki-v1.3\execution.py”，第 74 行，map_node_over_list results.append（getattr（obj， func）（**slice_dict（input_data_all， i））） 文件“D：\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantID\InstantID.py”，第 347 行，apply_instantid _set_model_patch_replace（work_model， patch_kwargs， （“输入”， id， 索引）） 文件“D：\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantID\InstantID.py”，第 136 行，_set_model_patch_replace to[“patches_replace”][“attn2”][key].add（instantid_attention， **patch_kwargs）

### ISSUE THREAD

**Issue by 31325-c** [cubiq/ComfyUI_InstantID#197]

**Comment by 31325-c** [comment]
执行 ApplyInstantIDAdvanced 时出错：

“CrossAttentionPatch”对象没有属性“add”

文件“D：\ComfyUI-aki-v1.3\execution.py”，第 151 行，recursive_execute
output_data，output_ui = get_output_data（obj， input_data_all）
文件“D：\ComfyUI-aki-v1.3\execution.py”，第 81 行，get_output_data
return_values = map_node_over_list（obj， input_data_all， obj.函数，allow_interrupt=True）
文件“D：\ComfyUI-aki-v1.3\execution.py”，第 74 行，map_node_over_list
results.append（getattr（obj， func）（**slice_dict（input_data_all， i）））
文件“D：\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantID\InstantID.py”，第 347 行，apply_instantid
_set_model_patch_replace（work_model， patch_kwargs， （“输入”， id， 索引））
文件“D：\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_InstantID\InstantID.py”，第 136 行，_set_model_patch_replace
to[“patches_replace”][“attn2”][key].add（instantid_attention， **patch_kwargs）

**Comment by GOODBOY199003** [comment]
I have the same problem, how to solve it?

**Comment by cubiq** [comment]
you need to update comfy and this extension, you have an old version installed
