### ISSUE TITLE
Bypassing InstantID cause washed out images

### ISSUE THREAD

**Issue by hortom** [cubiq/ComfyUI_InstantID#2]
Hi Cubiq,
Thank you very much for your work, I appreciate it.
I am a lazy user. If I add something to my workflow, I would rather mute or bypass it than remove it.
I grouped the important InstantID nodes.
<img src="https://github.com/cubiq/ComfyUI_InstantID/assets/1734567/1ecdd80e-78b7-449d-8a38-d65cd928e9db" width="200" >

Is it on comfyUI that bypassing doesn't work properly? If I bypass it, the result is a washed-out vs not using it.
<img src="https://github.com/cubiq/ComfyUI_InstantID/assets/1734567/2d111ed5-8c9f-4cf9-90b3-80a98225f6c6" width="200" > <img src="https://github.com/cubiq/ComfyUI_InstantID/assets/1734567/231f7022-86fd-47ad-85f3-19a974234da3" width="200" >

Did I do something wrong?

**Comment by cubiq** [comment]
that must be a bug with the groups. you probably need to bypass the IPAdapter and the controlnet nodes separately
