### ISSUE TITLE
I have tried your ComFyUI code, the results are probably better than Diffusers. What is the key for this quality ?

### ISSUE THREAD

**Issue by vuongminh1907** [cubiq/ComfyUI_InstantID#206]
![image](https://github.com/user-attachments/assets/7e4339be-ae22-4023-9a6c-04b0a27a6a87)

**Comment by cubiq** [comment]
possibly I do some normalization on the embeds that diffusers doesn't. I haven't checked the code in a while, but what I know is that the official implementation is released at day one and they rarely do any optimization later. I keep testing and trying new things

**Comment by vuongminh1907** [comment]
Thanks for your reply, I saw that you changed the IPAttnProcessor (Diffusers) by Attn2Replace, right ? Are there any changes you made, because I still can't figure out where you are using normalization. Thanks in advance.

**Comment by cubiq** [comment]
attention patching should be the same I guess, maybe some slight differences when applying kv and the controlnet. I haven't looked at diffusers code in a while, it's a monolithic library that I find frustrating to work with. Sorry I can't be of more help
