### ISSUE TITLE
Better Pose

### ISSUE THREAD

**Issue by skyler14** [cubiq/ComfyUI_InstantID#21]
The recently updated Huggingface demo incorporates several pose controlnets in lieu of its face keypoint detector. I was wondering if this could be implemented here as well, or is that demo just applying the face keypoint controlnet behind the scenes?

**Comment by cubiq** [comment]
The keypoints are added to an additional controlnet (any controlnet really) as you can see from here:

https://github.com/InstantID/InstantID/blob/main/infer_full.py#L112

This is already doable with the current implementation in ComfyUI.

![vram](https://github.com/cubiq/ComfyUI_InstantID/assets/427614/62c6439e-1fb4-421e-aaa6-9c9283a10986)

**Comment by JorgeR81** [comment]
Nice results ! 
It could be useful to add that workflow to the examples folder, as well.

**Comment by cubiq** [comment]
I will thanks
