### ISSUE TITLE
 ComfyUI_InstantID import does not work

### ISSUE THREAD

**Issue by CPLACKY** [cubiq/ComfyUI_InstantID#217]
<img width="806" alt="1" src="https://github.com/user-attachments/assets/11d0149b-f0f5-4fd9-b050-3640cb824700">
<img width="852" alt="instand id" src="https://github.com/user-attachments/assets/2d5686d9-a801-4802-b074-b0f9f016ad62">

how can i fix this T_T

**Comment by cubiq** [comment]
this is an environment configuration error. try to install everything from scratch. please keep the issue tracker only for bugs not support requests. Use the discord server linked in the readme if you need help
