### ISSUE TITLE
plz help, q1: the error show as below; 

### ISSUE THREAD

**Issue by celinecsw** [cubiq/ComfyUI_InstantID#228]
File "F:\celine\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\celine\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 13, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface.app'

Cannot import F:\celine\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID module for custom nodes: No module named 'insightface.app'

Import times for custom nodes:
   0.0 seconds: F:\celine\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: F:\celine\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds (IMPORT FAILED): F:\celine\ComfyUI_windows_portable\ComfyUI\custom_nodes\.vs
   0.0 seconds: F:\celine\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.0 seconds: F:\celine\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: F:\celine\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus-main
   0.0 seconds (IMPORT FAILED): F:\celine\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.2 seconds: F:\celine\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: F:\celine\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SAM2

**Comment by JJonC1995** [comment]
I am having the same issue. following for fix

**Comment by cubiq** [comment]
it's a problem with the installation of "insightface" we talked about this multiple time, please also check the ipadapter repository that uses the same library.
