### ISSUE TITLE
The weight is not functioning.

### ISSUE THREAD

**Issue by nomadoor** [cubiq/ComfyUI_InstantID#23]
![InstantID_weight_comparison](https://github.com/cubiq/ComfyUI_InstantID/assets/124905471/b101ad03-5125-4608-9b22-1572cb2c575f)
[InstantID_weight_comparison.json](https://github.com/cubiq/ComfyUI_InstantID/files/14284971/InstantID_weight_comparison.json)

I’ve noticed that regardless of the value of the weight in InstantID (including 0), the generated image hardly changes. 

The same goes for the attention_mask, whether it’s inputted or not, the same image is generated.

**Comment by cubiq** [comment]
please be sure to have the latest version installed

**Comment by nomadoor** [comment]
Just to be sure, I updated everything including the main ComfyUI, but the result is exactly the same as the image above🥴
Is there anything else I should check?

**Comment by cubiq** [comment]
you are not the first one reporting this but with the latest version I cannot replicate.

the "Apply InstantID" weight should contribute about 25% to the composition.

Examples below at 0.0 and at 1.0

![ComfyUI_temp_dizio_00044_](https://github.com/cubiq/ComfyUI_InstantID/assets/427614/1ead2d2d-daec-4d2b-914b-cda03f1828b3)

![ComfyUI_temp_dizio_00045_](https://github.com/cubiq/ComfyUI_InstantID/assets/427614/f398cbec-89af-4dee-992f-0eacc1e99fb5)

**Comment by nomadoor** [comment]
![InstantID_weight_comparison2](https://github.com/cubiq/ComfyUI_InstantID/assets/124905471/a2a7e38c-bcd0-4633-a301-ebf280beab7d)
When I changed the image input to FaceKeypointsPreprocessor, it started to output somewhat different images. 
I don’t quite understand InstantID, but does ControlNet play a bigger role than ip-adapter?

**Comment by cubiq** [comment]
like I said ip-adapter is about 25%, controlnet 75%

**Comment by nomadoor** [comment]
>the "Apply InstantID" weight should contribute about 25% to the composition.

Sorry, I didn’t get that at first, but now I do.
Your thoughts were really helpful. I’m now more interested in this technology!
Thank you for your time and insights.
