### ISSUE TITLE
Does this work with FLUX models?

### ISSUE THREAD

**Issue by ClothingAI** [cubiq/ComfyUI_InstantID#231]
?

**Comment by cubiq** [comment]
no

**Comment by ClothingAI** [comment]
Is it possible to make it work with it, or does that need to rewrite the code from scratch? @cubiq . I mean you encourage meto go ask for it in the official intant id repo?

**Comment by cubiq** [comment]
it needs the model to be retrained for flux

**Comment by ClothingAI** [comment]
OK thanks, and do you know other similar techniques for face swapping with FLUX? Per chance
