### ISSUE TITLE
Apply InstantID is very slow

### ISSUE THREAD

**Issue by WooXinyi** [cubiq/ComfyUI_InstantID#238]
Analyzing the ApplyInstantID node revealed that most of the time is spent moving the instantid model to the GPU with the code ‘self.instantid.to(self.device, dtype=self.dtype)’. (Solved it by updating the latest version)
Additionally, extracting face embeddings and keypoints also takes a considerable amount of time.

**Comment by cubiq** [comment]
the latest version should speed up the process quite a bit. regarding the embeds extraction there's little I can do about it I guess.
