### ISSUE TITLE
Could you provide the input images used in the multi-id workflow?

### ISSUE THREAD

**Issue by apsntian** [cubiq/ComfyUI_InstantID#24]
Hi, thanks for great work. 

could you provide the input images for example workflows? 

It is hard to understand  how the multi-id workflow works without them.

or please provide the captured image of multi-id workflow

**Comment by cubiq** [comment]
The are the images for the new multi-id workflow

![pose (1)](https://github.com/cubiq/ComfyUI_InstantID/assets/427614/56b10b93-c7ea-4e49-9765-ec388ae5b4d2)
![face4](https://github.com/cubiq/ComfyUI_InstantID/assets/427614/5c9b4ae5-b445-432e-8e34-d1cfd36590da)
![joseph-gonzalez-iFgRcqHznqg-unsplash](https://github.com/cubiq/ComfyUI_InstantID/assets/427614/9f13d205-35ac-4685-bada-287ba8e1112f)
