### ISSUE TITLE
15m on an L40?

### ISSUE THREAD

**Issue by jelling** [cubiq/ComfyUI_InstantID#25]
I'm using the multi workflow on an NVIDIA L40 (48 GB VRAM) and it's taking 15 minutes to infer an image. And this is true even after the first inferrence.

Is this normal?

```
root@4586373a9fa5:/# tail /workspace/logs/comfyui.log
Requested to load AutoencoderKL
Loading 1 new model
Prompt executed in 1365.37 seconds
got prompt
Requested to load SDXL
Requested to load ControlNet
Loading 2 new models
unload clone 0
100%|██████████| 30/30 [15:10<00:00, 30.35s/it]
Prompt executed in 981.00 seconds
root@4586373a9fa5:/#
```

**Comment by cubiq** [comment]
can you try with --gpu-only ?

**Comment by jelling** [comment]
That may have been it but I switched to a different provider that had a working Instant ID workflow already. And the performance was fine then. Thanks all the same.
