### ISSUE TITLE
[Feature Request maybe]Multiple Picture Reference Input

### ISSUE THREAD

**Issue by skyler14** [cubiq/ComfyUI_InstantID#26]
InstantID supports multiple pictures of the face as input, on A1111 I've found this really helps the model do better. I was wondering if there's a way to upload a stack of reference images in the nodes and if not you could add that

**Comment by cubiq** [comment]
this is already supported, just send a batch of images

**Comment by skyler14** [comment]
Is this done in one of your workflows?

**Comment by cubiq** [comment]
no, just use the batch image node
