### ISSUE TITLE
is it possible to not add any pose?

### ISSUE THREAD

**Issue by yanghu** [cubiq/ComfyUI_InstantID#28]
even in the "default" example, a pose is added to controlnet, by reusing the source image. 

I wonder if it's possible to NOT force pose but only rely on the text prompt, while only use the face to construct the human face?
Or is it not doable due to how instantID works?

I see in ZHOZHOZHO's implementation, pose image is "optional" in this screenshot:
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/5239196/88172f49-1a01-4ec5-8ea7-a5b529920751)
(source: https://openart.ai/workflows/rhinoceros_tense_89/zho-instantid-20/mAuBF4ArgVTwF5kzyB4t)

**Comment by cubiq** [comment]
without pose it looks like the face embeds are not applied at all, in which case it is the same as using just IPAdapter FaceID. I'll check the code better but the keypoints don't look optional (I mean I can make them optional but it's not how the model works)
