### ISSUE TITLE
controlnet not work for me

### ISSUE THREAD

**Issue by BingYYao** [cubiq/ComfyUI_InstantID#31]
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/104989192/d0095711-9df1-4cf3-9cf9-b8d1bd03f8b4)
When the process went through I tried to generate the image using the workflow InstantID_pose, but a bunch of noise appeared. When I tried to disable the controlnet node I found that I could generate it properly. Explaining that it is actually controlnet and ipa of instantid that is causing the noise. But I have checked that the models loaded are the ones specified. What can I do to solve this problem?

**Comment by cubiq** [comment]
duplicate https://github.com/cubiq/ComfyUI_InstantID/issues/5
