### ISSUE TITLE
any idea on the wired output? thanks

### ISSUE THREAD

**Issue by xghm** [cubiq/ComfyUI_InstantID#33]
Hi @cubiq, thanks for the update. I can successfully load the workflow. 

I didn't change any parameter but the output doesn't look expected. Do you have any idea what could be wrong? thanks!

<img width="1675" alt="image" src="https://github.com/cubiq/ComfyUI_InstantID/assets/121004726/fa879d9c-66c3-4b91-acdf-43c28e2c3997">

**Comment by cubiq** [comment]
you probably just need to update comfyUI

**Comment by xghm** [comment]
Updating comlyUI solved the problem, thank you!
