### ISSUE TITLE
a little suggestion

### ISSUE THREAD

**Issue by tanglup** [cubiq/ComfyUI_InstantID#35]
The initial version can combine multiple images of faces through image batches to enhance facial information, and the facial information is separated from the body posture map for better control. What do you think?

**Comment by tanglup** [comment]
Simplifying the unified node is good, but it would be better if it is set to only recognize facial information. Also, one of your menu options is an old version, and it doesn't work either. These are my suggestions and findings that the author can consider and pay attention to after washing. Of course, I respect your ideas and hope you can make the best plug-in.

**Comment by cubiq** [comment]
you can still do that.

send the batch to the "image" input and the keypoints for the controlnet to the image_kps input.

There's also an "advanced" model that lets you pick different weights for the instantid embeds and the controlnet

**Comment by tanglup** [comment]
Thank you for your reply. I just thought about it and your update is very good. I am also planning to update to the latest version.
