### ISSUE TITLE
Why are the generated results noisy images?

### ISSUE THREAD

**Issue by snsdyp** [cubiq/ComfyUI_InstantID#36]
I should have successfully installed and run the program, but the result of the generated image is a noisy image, as shown in the screenshot. Can you tell me what went wrong?
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/129200208/b520b3c5-1d9c-4b12-aa44-d7e71d632da3)

**Comment by cubiq** [comment]
https://github.com/cubiq/ComfyUI_InstantID/issues/33 duplicate
