### ISSUE TITLE
I have copies of ipadapter.bin everywhere except ...

### ISSUE THREAD

**Issue by Torcelllo** [cubiq/ComfyUI_InstantID#52]
... in this location! Where do I find the correct folder in which to put this? (LoadInstantIDModel)

![InstantID](https://github.com/cubiq/ComfyUI_InstantID/assets/114806454/af9f29d9-b9ae-4541-bf66-32d797e0f1c1)

**Comment by Torcelllo** [comment]
Sorted!

**Comment by ivanpoli** [comment]
> Sorted!

So where we should put it? I'm having the same question
