### ISSUE TITLE
Unable to generate two persons correctly using the multi-ID workflow

### ISSUE THREAD

**Issue by yunbinmo** [cubiq/ComfyUI_InstantID#54]
Hi, I am trying to use the example workflow  `InstantID_multi_id.json` to do multi-ID synthesis, I use portrait photo of two different faces as inputs and the sample `daydreaming.jpg` given in the repo as input to the controlnet (or should I use a photo of two persons?), but the output image seems to blend two faces together as seen below, am I doing anything wrong? I am using the `sd_xl_base_1.0_0.9vae.safetensors` checkpoint.

![image](https://github.com/cubiq/ComfyUI_InstantID/assets/77217780/2c1a9d84-c6c7-43cb-80ab-3375975d4f00)

After swap the two input image:
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/77217780/b95d37ef-72c5-4c79-bbd9-7b3a18012499)

Thanks!

**Comment by norsizu** [comment]
I guess your reference picture only has one character

**Comment by cubiq** [comment]
are the masks set correctly?

**Comment by norsizu** [comment]
I'm trying to figure out how to generate two-person pictures stably, too

**Comment by yunbinmo** [comment]
> are the masks set correctly?

Hi I didn't change the mask, it is the default mask set as below:
 
![Screenshot from 2024-02-26 15-10-02](https://github.com/cubiq/ComfyUI_InstantID/assets/77217780/be0d306b-9a4a-4142-99c5-3aa5539848dd)

And here's the overview of the graph, I only change the input images, everything else is untouched, all default from the given workflow
![Screenshot from 2024-02-26 15-11-12](https://github.com/cubiq/ComfyUI_InstantID/assets/77217780/6f3f8ac4-265f-4a1f-a26d-6bc00c7d4f3b)

**Comment by yunbinmo** [comment]
> I guess your reference picture only has one character

Do you mean the reference pose picture? If that's the case, I also tried using a reference pose picture of two character as below and the output image is even more weird:
![Screenshot from 2024-02-26 15-14-48](https://github.com/cubiq/ComfyUI_InstantID/assets/77217780/0ce67a3c-fba6-4dc4-adeb-2bb185614ee6)

**Comment by norsizu** [comment]
You should change the pose image to with two people in it.

**Comment by cubiq** [comment]
the pose image needs to be in the aspect ratio of the latent. in your example you are placing both characters in the middle so they overlap

**Comment by norsizu** [comment]
> > I guess your reference picture only has one character
> 
> Do you mean the reference pose picture? If that's the case, I also tried using a reference pose picture of two character as below and the output image is even more weird: ![Screenshot from 2024-02-26 15-14-48](https://private-user-images.githubusercontent.com/77217780/307695924-0ce67a3c-fba6-4dc4-adeb-2bb185614ee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzIwNDQsIm5iZiI6MTcwODkzMTc0NCwicGF0aCI6Ii83NzIxNzc4MC8zMDc2OTU5MjQtMGNlNjdhM2MtZmJhNi00ZGM0LWFkZWItMmJiMTg1NjE0ZWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA3MTU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NDZhMTAyYjRmMzBmNjFhNWFhMjg4MDBjNmY1ZDI3M2I0MTZiZDI2MTgwMTc0NTUzYzEzNThmODBjYTQ5M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-bZUtZkwmMDmCF1idV-ScaOUErjKcjvC8f6hF7JwhPY)

Generate it a few more times, I've had it come up with only one character. All I can say is that multi-ID workflow is just unstable right now.
