### ISSUE TITLE
Problem using mask

### ISSUE THREAD

**Issue by LukeG89** [cubiq/ComfyUI_InstantID#57]
I've tried using the mask option of InstantID, but the resulting image will be generated only inside the masked area. 

This is the image without masking:
![InstantID_test_no_mask](https://github.com/cubiq/ComfyUI_InstantID/assets/161304036/647d0160-701b-4942-b181-cad4b05ef3c9)

And this with the mask applied:
![InstantID_test_with_mask](https://github.com/cubiq/ComfyUI_InstantID/assets/161304036/601a8b63-0797-446a-9128-a2f7edbc7b33)

I think the issue is caused by ControlNet inside your node. Before the latest update I had encountered the same situation when appling the mask to ControlNet using the `mask_optional` of _Advanced ControlNet_ node. 

Maybe attention mask and ControlNet mask are merged together?

**Comment by cubiq** [comment]
as it is now you get the lowest amount of embeds bleeding. This is not (only) an attention mask but also a conditioning mask.

If you want to mask you need to define all areas like with any other conditioning mask
