### ISSUE TITLE
Failed results with Apply ControlNet in the pipeline 

### ISSUE THREAD

**Issue by wandrzej** [cubiq/ComfyUI_InstantID#6]
<img width="1499" alt="image" src="https://github.com/cubiq/ComfyUI_InstantID/assets/26924000/18f66b78-3fd0-470c-9397-a3eb04fb6bfa">
I tried to replicate the workflow you showcase. If I pass both through the controlnet and apply instand ID I get those "empty canvas" images. 
If I just pass the Apply InstantID it works to an extent - the resemblance for sure isn't anything close to what can be seen in the paper, but it's also not accidental - here an old woman with grey hair, gives another woman with grey hair
<img width="1339" alt="image" src="https://github.com/cubiq/ComfyUI_InstantID/assets/26924000/1ee980d1-5b12-46e1-ae89-0fd708030ce7">

**Comment by skeyic** [comment]
I got the same issue

**Comment by cubiq** [comment]
you need to update comfyui

**Comment by wandrzej** [comment]
OK, that helped. Still not sure what the face keypoints preprocessor via CN and the InstantID CN suppose to be doing :)  , but issue is resolved

**Comment by LubuLubu2** [comment]
> OK, that helped. Still not sure what the face keypoints preprocessor via CN and the InstantID CN suppose to be doing :) , but issue is resolved

I guess face keypoints preprocessor marks a spot on a latent for face and it's position, you can add any refrence image to it (doesn't have to be anything similar to your original image but it's sensitive to aspect ratio) and it generates the face and it's position on that spot, you can also add an image preview nod at output of keypoint nod to see how it sees it.
