### ISSUE TITLE
when i sent 0 in "start_at",the result is this

### ISSUE THREAD

**Issue by 1363887892** [cubiq/ComfyUI_InstantID#63]
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/102472409/77612586-0ee3-45b9-a178-a10f7aecb42c)
but when sent 1,it s ok
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/102472409/98682952-8f78-4491-a4c2-2da2bb496f71)

**Comment by 1363887892** [comment]
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/102472409/4c01c8fd-cb55-4611-961f-53af0d4bad04)
lol,i have change the node with a  advented node,and the quetion is OK

**Comment by cubiq** [comment]
you need to update comfyui
