### ISSUE TITLE
can't generate normal image?

### ISSUE THREAD

**Issue by liaoxy169** [cubiq/ComfyUI_InstantID#66]
i can't generate normal image use instantid
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/20810977/1671387f-571e-43ee-8358-d92a0fa9002a)
but if i lower the weight of the instantid, i get a normal image:
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/20810977/86c34dfd-0dd7-4a6f-83ea-8a71770fbe0c)
no warning no error:
![image](https://github.com/cubiq/ComfyUI_InstantID/assets/20810977/ac7c407d-b8c5-4bf2-ad19-9a1755f4e85d)

**Comment by cubiq** [comment]
https://github.com/cubiq/ComfyUI_InstantID/issues/36
