### ISSUE TITLE
InstantID overwrites IPAdapter now

### ISSUE THREAD

**Issue by JoeNavark** [cubiq/ComfyUI_InstantID#7]
Thanks for fixing that error last night. However, now having instantid and it's controlnet both set at 0weight  blocks any input from ipadapter even at super high weight.

**Comment by JoeNavark** [comment]
Well it's only an issue if instantid is after other adapters in the chain, so easy enough to work around.

**Comment by cubiq** [comment]
I'll have a better look at it when I have time, should be an easy fix

**Comment by cubiq** [comment]
PS: you need to update IPAdapter too
