### ISSUE TITLE
Error HSA_STATUS_ERROR_OUT_OF_REGISTERS

### ISSUE THREAD

**Issue by simonefelli** [cubiq/ComfyUI_InstantID#71]
Ciao Matteo
Got this error when Ksampler starts:

_:0:rocdevice.cpp :2728: 10087868149 us: [pid:20536 tid:0x7fb428fff640] Callback: Queue 0x7fb226400000 aborting with error : HSA_STATUS_ERROR_OUT_OF_REGISTERS: Kernel has requested more VGPRs than are available on this agent code: 0x2d
Aborted (core dumped)_

I'm on Linux (ubuntu 22.04):
Total VRAM 8176 MB, total RAM 32029 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 7600 : native
VAE dtype: torch.float32
Workflow: InstantID_basic.json

Any clues as to what it could be?
Thanks

**Comment by cubiq** [comment]
try to run comfy in force-fp16 mode

**Comment by simonefelli** [comment]
No luck with force-fp16, anyway thank you for your work, it's awesome!

**Comment by cubiq** [comment]
that feels like a driver issue, very difficult for me to escalate, maybe update rocm if you haven't already?

**Comment by simonefelli** [comment]
Yes, I think it's a rocm issue too. I'm using latest 6.0.2 so I'll just wait for a new version to come and then try again. Should I close this Issue?
Grazie 1000 :)
