### ISSUE TITLE
Why does it generate strange pictures

### ISSUE THREAD

**Issue by delcompan** [cubiq/ComfyUI_InstantID#76]
Why do the pictures I generate using instantID have a cross?

![20240304-173900_00001](https://github.com/cubiq/ComfyUI_InstantID/assets/29897447/2b54ad35-a6f9-483b-b0e5-ec592edf6343)
[instatID_workflow.json](https://github.com/cubiq/ComfyUI_InstantID/files/14479565/instatID_workflow.json)

**Comment by cubiq** [comment]
I cannot replicate with the included workflow, you probably have an older version installed

**Comment by delcompan** [comment]
I just installed it today via comfyui Manager, it should be the latest. This is my first time using it. The main model I use is devlishphotorealism_sdxl15.safetensors, is it related to this?

**Comment by cubiq** [comment]
the images you generated don't seem made with the attached workflow.

I don't think the checkpoint you use can make a difference

**Comment by delcompan** [comment]
These pictures contain workflows. I was worried that the picture information would change after uploading, so I uploaded three pictures in a package.
![20240304-180108_00001](https://github.com/cubiq/ComfyUI_InstantID/assets/29897447/b2cd8094-0a2d-4010-ad7c-6b63b3bca62a)
![20240304-180238_00001](https://github.com/cubiq/ComfyUI_InstantID/assets/29897447/73706511-bea4-46b3-acd6-6d7802f77891)
![ComfyUI_temp_azpdk_00001_](https://github.com/cubiq/ComfyUI_InstantID/assets/29897447/814e2724-87cb-4cef-bc2e-db395eef49be)
[strange images.zip](https://github.com/cubiq/ComfyUI_InstantID/files/14479894/strange.images.zip)

**Comment by cubiq** [comment]
with your workflow I get this

![ComfyUI_temp_xbqog_00035_](https://github.com/cubiq/ComfyUI_InstantID/assets/427614/917949d0-03d0-4363-961d-60c984ae8a28)

**Comment by delcompan** [comment]
This question is so strange

![workflow](https://github.com/cubiq/ComfyUI_InstantID/assets/29897447/4b9d17b9-064d-47e7-be0f-481eff90ad0c)

**Comment by cubiq** [comment]
the controlnet is not actually applied. be sure to use the right controlnet model and also upgrade ComfyUI

**Comment by delcompan** [comment]
Thank you for your help, the issue has been resolved. The two models used by instantID are automatically downloaded at runtime of the workflow. After re-downloading these two files, everything runs perfectly again.
![Uploading workflow-2.png…]()

**Comment by delcompan** [comment]
![workflow-2](https://github.com/cubiq/ComfyUI_InstantID/assets/29897447/5d7aa3e8-d03a-4f94-9a47-c894e1eb4981)

**Comment by cubiq** [comment]
that is a bug of the manager, you should probably report it to them

**Comment by EricR0405** [comment]
Delcompan, I got the same problem, it’s really a problem with diffusion_pytorch. After connecting to the Webui directory, I selected the wrong model. After renaming it, it was solved. The portrait started to look similar to the reference picture, and no cross appeared.Thanks for your information.
