### ISSUE TITLE
the real reason for generating weird Images

### ISSUE THREAD

**Issue by delcompan** [cubiq/ComfyUI_InstantID#77]
the previous issue: https://github.com/cubiq/ComfyUI_InstantID/issues/76#issue-2166409954

At first, I thought the model was the problem. When I re-downloaded and renamed the model to "diffusion_pytorch_model-1.safetensors" and placed it in the same directory, everything worked fine. But when I changed the file name back to the default "diffusion_pytorch_model.safetensors," those strange images popped up again. After digging into the ControlNet directory structure, I realized that I had set up "a1111" in the extra_model_paths.yaml file to easily use the ControlNet model downloaded from sdwebui. Turns out, there was a 4GB file with the same name "diffusion_pytorch_model.safetensors" in sdwebui's ControlNet, and I totally forgot what that model was for.
<img width="359" alt="models-" src="https://github.com/cubiq/ComfyUI_InstantID/assets/29897447/bd57e772-4c57-4cfa-974f-1031b4bbd3ee">

When I left-clicked to choose the model in comfyui's Load ControlNet Model node, even if I correctly selected the "diffusion_pytorch_model.safetensors" from the InstantId directory, the final node still displayed the file as "diffusion_pytorch_model.safetensors." 
<img width="424" alt="models-2" src="https://github.com/cubiq/ComfyUI_InstantID/assets/29897447/e0a85526-f26c-46c4-8aec-3606a4fee159">

It should have shown "instantId/diffusion_pytorch_model.safetensors." 
<img width="418" alt="models-1" src="https://github.com/cubiq/ComfyUI_InstantID/assets/29897447/836c2e20-2e8c-478c-91de-13dc43400f73">

This means I was actually choosing the wrong model. The fix? Don't left-click to select the model; instead, use the triangles on both sides of the selection box to make sure you're choosing the right model file. Better yet, just rename the model to "instantid_diffusion_pytorch_model.safetensors" to avoid any mix-ups. I hope that makes sense!
I'm not sure if this counts as a bug in the Load ControlNet Model.

**Comment by cubiq** [comment]
thanks for your feedback
