### ISSUE TITLE
Failed to validate prompt

### ISSUE THREAD

**Issue by CactusBrothers** [cubiq/ComfyUI_InstantID#8]
When running the default example workflow I'm getting the folowing error

![image](https://github.com/cubiq/ComfyUI_InstantID/assets/94794504/783d95b8-a5bf-42c6-ab74-a1dcb4ba8088)
ERROR:root:Failed to validate prompt for output 15:
ERROR:root:* ApplyInstantID 57:
ERROR:root:  - Return type mismatch between linked nodes: insightface, FACEANALYSIS != INSIGHTFACE
ERROR:root:  - Required input is missing: image
ERROR:root:* ControlNetApplyAdvanced 23:
ERROR:root:  - Exception when validating inner node: tuple index out of range
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

I am using the latest comfyui, instantID and ipadapter-plus custom nodes.

It looks like the node inputs and outputs dont match up, but apparently others can run this and I dont know why. Thanks for making this and thanks in advance for any help!

**Comment by cubiq** [comment]
you probably have cached an older version. Delete the InstantID node, refresh the page a couple of times and create a new one. If it doesn't work try with an incognito window

**Comment by CactusBrothers** [comment]
I tried, but when I delete the "Apply InstandID" node and try to add it again, it doesnt have the "positive" and "negative" inputs somehow

**Comment by cubiq** [comment]
for some reason your installation is broken. Be sure to remove other InstantID extensions if you have them and reinstall this one from scratch.

**Comment by CactusBrothers** [comment]
I had the old placeholderInstandID still installed 😞 Sorry for the inconvenience... It works now
