### ISSUE TITLE
[Question] Why Face Analysis Preprocessor stop working with multiple images?

### ISSUE THREAD

**Issue by LukeG89** [cubiq/ComfyUI_InstantID#80]
Hi @cubiq, I have a question about multiple reference images.

In previous commits, from `3fa938f` (First working version) to `5149a21`, Face Analysis preprocessor was working with multiple images, both using single images and video frames.

![Face_Analysis_with_batches](https://github.com/cubiq/ComfyUI_InstantID/assets/161304036/fcadab91-c8b1-47d2-a16b-a469f2042421)

https://github.com/cubiq/ComfyUI_InstantID/assets/161304036/c395007a-f63f-442a-a3e0-4578233ff942

But after `6938fc7` (bugfix), Face Analysis only recognize the first image. Why is that?

Thanks a lot!

**Comment by cubiq** [comment]
this was done because you can send a batch of reference images that are averaged, but only 1 kps position was used.

now you can send a batch a images for the kps image

**Comment by LukeG89** [comment]
Great update, @cubiq! Thank you very much! 

Now I go off-topic and start speaking italian (in italic of course): 
_Volevo cogliere l'occasione per ringraziarti di tutto ciò che fai per questa community, apprezzo moltissimo l'impegno che ci metti nel tuo lavoro e la passione che hai anche nell'insegnare. Sei davvero fantastico, Matteo! Continua così!_ :)

**Comment by cubiq** [comment]
grazie!
