### ISSUE TITLE
Default Problem with workflow 

### ISSUE THREAD

**Issue by hotlml** [cubiq/ComfyUI_InstantID#82]
![屏幕截图 2024-03-06 103241](https://github.com/cubiq/ComfyUI_InstantID/assets/74162310/ae54ed81-16ec-41a0-b8c6-cb62de09a9b6)
The comfyui instantid node in the workflow is not working properly。

**Comment by cubiq** [comment]
delete the node, upgrade the extension, restart comfy, refresh the page, recreate the node

**Comment by hotlml** [comment]
Thanks, I'll give it a try.
________________________________
发件人: Matteo Spinelli ***@***.***>
发送时间: 2024年3月6日 14:08
收件人: cubiq/ComfyUI_InstantID ***@***.***>
抄送: hotlml ***@***.***>; Author ***@***.***>
主题: Re: [cubiq/ComfyUI_InstantID] Default Problem with workflow (Issue #82)


delete the node, upgrade the extension, restart comfy, refresh the page, recreate the node

―
