### ISSUE TITLE
Why can't I control the character's line of sight?

### ISSUE THREAD

**Issue by Datou** [cubiq/ComfyUI_InstantID#86]
The line of sight of characters generated using instantid is very random. I tried adding looking at viewer to the prompt word, but it had no effect. I tried using pose controlnet to control the line of sight, but it had no effect. Is there any way to control sight?
![img__00144_](https://github.com/cubiq/ComfyUI_InstantID/assets/15013/bbf6a012-2a0a-457b-bef5-cf03650cb62e)
![img__00156_](https://github.com/cubiq/ComfyUI_InstantID/assets/15013/e6b0da2c-fc2b-469e-8cae-abceddc5493c)

**Comment by cubiq** [comment]
that's completely up to the checkpoint that you use

**Comment by Datou** [comment]
> that's completely up to the checkpoint that you use

My friend tested and found that the direction of the gaze can be controlled by the facial image passed to IPA.
![537b3f5687ef07afbc3f8bde82f40e1](https://github.com/cubiq/ComfyUI_InstantID/assets/15013/02afd7bb-688a-4821-b548-893cf6539202)
![a6e331d2425954e955a7506ad0b07dd](https://github.com/cubiq/ComfyUI_InstantID/assets/15013/ee1e69be-fc39-4ed5-8816-8814d6193c48)
