### ISSUE TITLE
Is there a way to batch process kps images in Apply InstantID?

### ISSUE THREAD

**Issue by ManOrMonster** [cubiq/ComfyUI_InstantID#99]
I love the feature that allows sending batched face images in order to combine them into one, but I'd also like to send a batch of kps images to batch process them in one sampler pass. Currently "Apply InstantID" only takes one kps image when a batch is sent. I can send a list of images to the node and have it sample one at a time, but that's slower than a batch would be.

Is this planned, or even possible?

**Comment by cubiq** [comment]
it works already

![image](https://github.com/cubiq/ComfyUI_InstantID/assets/427614/5d712a28-e385-4618-bb6b-ffc1b34985e3)

**Comment by ManOrMonster** [comment]
OK, my brain is fried. I completely forgot that I have to manually set the batch number in the Empty Latent Image node. I also just now learned that I don't need to use KPS pose images or the Face Keypoints Preprocessor to get face poses.

Thanks for the help!
